---
- hosts: 10.35.65.105
  gather_facts: no
  tasks:
          #    - name: Copy war file to tower
          # copy:
          #  src: "/home/psr/shared/00_deploy_ekspress_prod/deployment/{{ war_file }}"
          # dest: "/data/express/war/{{ war_file }}"
          # remote_src: yes
          #    register: copy


    - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
      fetch:
        src: "/home/psr/shared/00_deploy_ekspress_prod/deployment/{{ war_file }}"
        dest: "/data/express/war/{{ war_file }}"
        flat: yes
      register: copy
